name: .NET Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  Solution_Name: Calculator.sln
  Test_Project_Path: ICT3101_Calculator.UnitTests
  SpecFlow_Test_Project_Path: SpecFlowCalculatorTests

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}
      
    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --no-restore
      
    - name: NUnit Tests
      working-directory: ICT3101_Calculator.UnitTests/
      run: dotnet test --no-build --verbosity normal
      
    - name: SpecFlow Tests
      working-directory: SpecFlowCalculatorTests/
      run: dotnet test --no-build --verbosity normal